/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { AmountDeriver, AmountDeriverInterface } from "../AmountDeriver";

const _abi = [
  {
    inputs: [],
    name: "InexactFraction",
    type: "error",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220754e39275ed9836ebb59191fe5f75dd7a480172c958c7227f4224c495e70d05364736f6c634300080d0033";

type AmountDeriverConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AmountDeriverConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AmountDeriver__factory extends ContractFactory {
  constructor(...args: AmountDeriverConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "AmountDeriver";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<AmountDeriver> {
    return super.deploy(overrides || {}) as Promise<AmountDeriver>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): AmountDeriver {
    return super.attach(address) as AmountDeriver;
  }
  connect(signer: Signer): AmountDeriver__factory {
    return super.connect(signer) as AmountDeriver__factory;
  }
  static readonly contractName: "AmountDeriver";
  public readonly contractName: "AmountDeriver";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AmountDeriverInterface {
    return new utils.Interface(_abi) as AmountDeriverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AmountDeriver {
    return new Contract(address, _abi, signerOrProvider) as AmountDeriver;
  }
}
