/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  CriteriaResolution,
  CriteriaResolutionInterface,
} from "../CriteriaResolution";

const _abi = [
  {
    inputs: [],
    name: "ConsiderationCriteriaResolverOutOfRange",
    type: "error",
  },
  {
    inputs: [],
    name: "CriteriaNotEnabledForItem",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidProof",
    type: "error",
  },
  {
    inputs: [],
    name: "OfferCriteriaResolverOutOfRange",
    type: "error",
  },
  {
    inputs: [],
    name: "OrderCriteriaResolverOutOfRange",
    type: "error",
  },
  {
    inputs: [],
    name: "UnresolvedConsiderationCriteria",
    type: "error",
  },
  {
    inputs: [],
    name: "UnresolvedOfferCriteria",
    type: "error",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220932ca51c199e95cd29e7cd97daf017a9f80a48e2061a68dd00d15895b86f3e2764736f6c634300080d0033";

type CriteriaResolutionConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CriteriaResolutionConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CriteriaResolution__factory extends ContractFactory {
  constructor(...args: CriteriaResolutionConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "CriteriaResolution";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<CriteriaResolution> {
    return super.deploy(overrides || {}) as Promise<CriteriaResolution>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): CriteriaResolution {
    return super.attach(address) as CriteriaResolution;
  }
  connect(signer: Signer): CriteriaResolution__factory {
    return super.connect(signer) as CriteriaResolution__factory;
  }
  static readonly contractName: "CriteriaResolution";
  public readonly contractName: "CriteriaResolution";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CriteriaResolutionInterface {
    return new utils.Interface(_abi) as CriteriaResolutionInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CriteriaResolution {
    return new Contract(address, _abi, signerOrProvider) as CriteriaResolution;
  }
}
