/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  FulfillmentApplier,
  FulfillmentApplierInterface,
} from "../FulfillmentApplier";

const _abi = [
  {
    inputs: [],
    name: "InvalidFulfillmentComponentData",
    type: "error",
  },
  {
    inputs: [],
    name: "MismatchedFulfillmentOfferAndConsiderationComponents",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "enum Side",
        name: "side",
        type: "uint8",
      },
    ],
    name: "MissingFulfillmentComponentOnAggregation",
    type: "error",
  },
  {
    inputs: [],
    name: "OfferAndConsiderationRequiredOnFulfillment",
    type: "error",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220ff832cec6960c950148b5b7484f4fbd9640bf4b12a18fd212204a71a44737c0864736f6c634300080d0033";

type FulfillmentApplierConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: FulfillmentApplierConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class FulfillmentApplier__factory extends ContractFactory {
  constructor(...args: FulfillmentApplierConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "FulfillmentApplier";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<FulfillmentApplier> {
    return super.deploy(overrides || {}) as Promise<FulfillmentApplier>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): FulfillmentApplier {
    return super.attach(address) as FulfillmentApplier;
  }
  connect(signer: Signer): FulfillmentApplier__factory {
    return super.connect(signer) as FulfillmentApplier__factory;
  }
  static readonly contractName: "FulfillmentApplier";
  public readonly contractName: "FulfillmentApplier";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FulfillmentApplierInterface {
    return new utils.Interface(_abi) as FulfillmentApplierInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FulfillmentApplier {
    return new Contract(address, _abi, signerOrProvider) as FulfillmentApplier;
  }
}
